### ISSUE TITLE
config.xml. Error : null

### ISSUE THREAD

**Issue by Vove7** [etiennestuder/gradle-jooq-plugin#103]
my build.gradle:
```
jooq {
    version = '3.11.11' // the default (can be omitted)
    sample(sourceSets.main) {
        jdbc {
            driver = 'com.mysql.cj.jdbc.Driver'
            url = 'jdbc:mysql://xx.xx.xx/xxx'
            user = 'root'
            password = '*****'
            properties {
                property {
                    key = 'useSSL'
                    value = 'false'
                }
            }
        }
    }
}
```
then `gradle generateSampleJooqSchemaSource` and failed: 

```
> Task :generateSampleJooqSchemaSource FAILED
8 31, 2019 10:56:34  org.jooq.tools.JooqLogger info
Ϣ: Initialising properties  : xxxxx\build\tmp\generateSampleJooqSchemaSource\config.xml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/xxxxx/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-impl/2.3.0.1/2e979dabb3e5e7
4a0686115075956391a14dece8/jaxb-impl-2.3.0.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
8 31, 2019 10:56:35  org.jooq.tools.JooqLogger info
Ϣ: Database                 : Inferring database org.jooq.meta.mysql.MySQLDatabase from URL jdbc:mysql://xx.xx.xx/xxxxx
8 31, 2019 10:56:35  org.jooq.tools.JooqLogger info
Ϣ: No <inputCatalog/> was provided. Generating ALL available catalogs instead.
8 31, 2019 10:56:35  org.jooq.tools.JooqLogger info
Ϣ: No <inputSchema/> was provided. Generating ALL available schemata instead.
8 31, 2019 10:56:35  org.jooq.tools.JooqLogger error
: Cannot read xxxx\build\tmp\generateSampleJooqSchemaSource\config.xml. Error : null
java.lang.NullPointerException
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:503)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:222)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:194)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateSampleJooqSchemaSource'.
> Process 'command 'F:\Program Files\Java\jdk-11.0.3\bin\java.exe'' finished with non-zero exit value -1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed

```
**java8 too**

### config.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd">
    <jdbc>
        <driver>com.mysql.cj.jdbc.Driver</driver>
        <url>jdbc:mysql://xx.xx.xx/xxx</url>
        <user>root</user>
        <password>*******</password>
        <properties>
            <property>
                <key>useSSL</key>
                <value>false</value>
            </property>
        </properties>
    </jdbc>
    <generator>
        <name>org.jooq.codegen.DefaultGenerator</name>
        <target>
            <packageName>nu.studer.sample</packageName>
            <directory>build/generated-src/jooq/sample/</directory>
            <encoding>UTF-8</encoding>
            <clean>true</clean>
        </target>
    </generator>
</configuration>
```

**Comment by etiennestuder** [comment]
If this config.xml triggers a NPE when the jooq code generation runs (and assuming the xml is valid), then I suggest you open an issue with the jooq project.

**Comment by itanoss** [comment]
I had the same problem.
Here is my resolution.
`generator.database` should be specified.

```gradle
jooq {
    sample(sourceSets.main) {
        jdbc {
        // ..
        }
        generator {
            database {
            }
        }
    }
}
```
