### ISSUE TITLE
`Database` section is not included in the generated config.xml

### ISSUE THREAD

**Issue by knrybarczyk** [etiennestuder/gradle-jooq-plugin#132]
Hi,

I have configured the jooq plugin in my `build.gradle.kts` file:

```
jooq {
    version = Versions.jooq

    val dbHost = System.getenv("DB_HOST")
    val dbUser = System.getenv("DB_USER")
    val dbPassword = System.getenv("DB_PASSWORD")
    val configuration = Configuration()
    
    configuration.apply {
        logging = org.jooq.meta.jaxb.Logging.WARN

        jdbc = Jdbc().apply {
            driver = "org.postgresql.Driver"
            url = "jdbc:postgresql://$dbHost/postgres"
            user = dbUser
            password = dbPassword
        }

        generator = Generator().apply {
            database = Database().apply {
                name = "org.jooq.meta.postgres.PostgresDatabase"
                inputSchema = "public"
            }
            generate = Generate().apply {
                isJavaTimeTypes = true
            }
        }
    }

    whenConfigAdded.invoke(JooqConfiguration("sample", sourceSets["main"], configuration))
}
```

When I run the `generateSampleJooqSchemaSource` task I get the following error:

```
> Task :generateChatJooqSchemaSource FAILED
Jul 28, 2020 9:08:38 AM org.jooq.tools.JooqLogger info
INFO: Initialising properties  : /Users/user/code/sample/build/tmp/generateSampleJooqSchemaSource/config.xml
Jul 28, 2020 9:08:39 AM org.jooq.tools.JooqLogger error
SEVERE: Cannot read /Users/user/code/sample/build/tmp/generateSampleJooqSchemaSource/config.xml. Error : null
java.lang.NullPointerException
	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:555)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:222)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:217)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:189)


Execution failed for task ':generateChatJooqSchemaSource'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-11.0.3.jdk/Contents/Home/bin/java'' finished with non-zero exit value 255
```

Upon investigation of `config.xml` I noticed there is no section for `generator.database`:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.13.0.xsd">
    <logging>WARN</logging>
    <onError>FAIL</onError>
    <jdbc>
        <driver>org.postgresql.Driver</driver>
        <url>jdbc:postgresql://localhost/postgres</url>
        <user>docker</user>
    </jdbc>
    <generator>
        <name>org.jooq.codegen.DefaultGenerator</name>
        <target>
            <packageName>org.jooq.generated</packageName>
            <directory>build/generated-src/jooq/sample</directory>
            <encoding>UTF-8</encoding>
            <clean>true</clean>
        </target>
    </generator>
</configuration>
```

**Comment by etiennestuder** [comment]
This plugin is not geared towards the Groovy DSL, not the Kotlin DSL. Thus, I cannot help you with your issue. Maybe someone from the jOOQ community using the Gradle Kotlin DSL can help you.

**Comment by etiennestuder** [comment]
You might want to take a look at this example: https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_kotlin_dsl/build.gradle.kts

Notice the `buildSrc` project.

**Comment by knrybarczyk** [comment]
Thanks, I've ended up not using the plugin. It's a shame it doesn't work with the Kotlin DSL

**Comment by etiennestuder** [comment]
As of 5.x, the gradle-jooq-plugin supports the Gradle Kotlin DSL as a first-class citizen. See the README file:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md

See this complete example written with the Gradle Kotlin DSL:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_kotlin_dsl/build.gradle.kts
