### ISSUE TITLE
failing to inject compile args

### ISSUE THREAD

**Issue by iceback** [etiennestuder/gradle-jooq-plugin#157]
Is is possible to have the plugin use --enable-preview?  I'm trying move forward from java 11.

I have add these directives to the build file

   compileJava {
     options.compilerArgs += ['--enable-preview', '--source 15']
   }

   tasks.withType(JavaCompile) {
     options.compilerArgs += ['--enable-preview', '-parameters']
   }
   tasks.withType(JavaExec) {
     jvmArgs.compilerArgs += ['--enable-preview', '--source 15']
   }

but I get this report

   > Task :jooq:generateJooq FAILED
   Dec 04, 2020 3:07:10 PM org.jooq.tools.JooqLogger warn
   WARNING: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 6235; cvc-complex-type.2.4.a: Invalid content was found starting with element ...
   WARNING: An illegal reflective access operation has occurred
   WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/home/rob/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-impl/2.3.0.1/2e979dabb3e5e74a0686115075956391a14dece8/jaxb-impl-2.3.0.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
   WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
   WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
   WARNING: All illegal access operations will be denied in a future release
   Exception in thread "main" java.lang.UnsupportedClassVersionError: Preview features are not enabled for edu/utah/camplab/jooq/JxonAnnotationGenerator (class file version 59.65535). Try running with '--enable-preview'
	   at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	   at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	   at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	   at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:825)
	   at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
	   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
	   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	   at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	   at java.base/java.lang.Class.forName0(Native Method)
	   at java.base/java.lang.Class.forName(Class.java:377)
	   at org.jooq.codegen.GenerationTool.loadClass0(GenerationTool.java:1070)
	   at org.jooq.codegen.GenerationTool.loadClass(GenerationTool.java:1003)
	   at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:382)
	   at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
	   at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
	   at org.jooq.codegen.GenerationTool.main(GenerationTool.java:200)

The JxonAnnotationGenerator is made in a dependent project and I've manually insured the javac --enable-preview -parameters are used in generating that extension.

Is the class file version reported even believable? 59.65535 (2^16 - 1)

**Comment by etiennestuder** [comment]
@iceback you can control the jvm args passed to the JVM that executes jOOQ as shown in this example:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/configure_jvm_args/build.gradle#L41-L46

**Comment by etiennestuder** [comment]
Maybe also take a look at this:
https://github.com/etiennestuder/gradle-jooq-plugin/issues/149

**Comment by iceback** [comment]
Thank you!  This issue can be closed.

I have since also deduced the failing in my approach:


    tasks.withType(JavaExec) {
       jvmArgs*.compilerArgs* += ['--enable-preview']
    }

vs

    tasks.withType(JavaExec) {
       jvmArgs += ['--enable-preview']
    }

Both correct approaches come to the same conclusion:

    SEVERE: Cannot read
    /home/rob/gits/gitlab/sgs4/jooq/build/tmp/generateJooq/config.xml.
    Error : Error generating code for catalog
    org.jooq.codegen.GeneratorException: Error generating code for catalog
         at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:441)
         at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:879)
         at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
         at
    org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
         at org.jooq.codegen.GenerationTool.main(GenerationTool.java:200)
    Caused by: java.lang.NullPointerException: Cannot invoke
    "String.length()" because "this.packageName" is null

So I have more digging to do since this failure corresponds to moving to 
java 15.
