### ISSUE TITLE
Spring Boot - Your configured database type was not found: org.jooq.meta.extensions.jpa.JPADatabase

### ISSUE THREAD

**Issue by StefanHaunsberger** [etiennestuder/gradle-jooq-plugin#167]
Hi,

I'm trying to set up Jooq using the Gradle plugin v. 5.2.1 with Spring Boot (v. 2.4.3) using the `JPADatabase`. 
However, the console output shows me that the `JPADatabase` extension cannot be found with the following error:

```console
> Task :generateJooq FAILED
Mar 12, 2021 9:17:59 AM org.jooq.tools.JooqLogger info
INFO: Initialising properties  : <project>/jooq/build/tmp/generateJooq/config.xml
Mar 12, 2021 9:17:59 AM org.jooq.tools.JooqLogger warn
WARNING: Type not found           : Your configured database type was not found: org.jooq.meta.extensions.jpa.JPADatabase.
- Please make sure the jooq-meta-extensions-hibernate dependency is on your classpath.
- In jOOQ 3.14, the dependency name has changed, see https://github.com/jOOQ/jOOQ/issues/10331
Mar 12, 2021 9:07:23 AM org.jooq.tools.JooqLogger error
SEVERE: Error in file: <project>/jooq/build/tmp/generateJooq/config.xml. Error : Your configured database type was not found: org.jooq.meta.extensions.jpa.JPADatabase.
- Please make sure the jooq-meta-extensions-hibernate dependency is on your classpath.
- In jOOQ 3.14, the dependency name has changed, see https://github.com/jOOQ/jOOQ/issues/10331
java.lang.ClassNotFoundException: Your configured database type was not found: org.jooq.meta.extensions.jpa.JPADatabase.
- Please make sure the jooq-meta-extensions-hibernate dependency is on your classpath.
- In jOOQ 3.14, the dependency name has changed, see https://github.com/jOOQ/jOOQ/issues/10331
        at org.jooq.codegen.GenerationTool.loadClass(GenerationTool.java:1066)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:413)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:200)
Caused by: java.lang.ClassNotFoundException: org.jooq.meta.extensions.jpa.JPADatabase
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.jooq.codegen.GenerationTool.loadClass0(GenerationTool.java:1075)
        at org.jooq.codegen.GenerationTool.loadClass(GenerationTool.java:1005)
        ... 4 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateJooq'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 255
```

### build.gradle

```gradle
buildscript {
	ext {
		springBootVersion = '2.4.3'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

plugins {
	id 'org.springframework.boot' version '2.4.3'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
	id 'nu.studer.jooq' version '5.2.1'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'com.h2database:h2'
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }

	implementation 'org.springframework.boot:spring-boot-starter-jooq'
	implementation group: 'org.jooq', name: 'jooq-codegen'
	implementation group: 'org.jooq', name: 'jooq-meta-extensions-hibernate'
}

test {
	useJUnitPlatform()
}

jooq {
    // use jOOQ version defined in Spring Boot
    version = dependencyManagement.importedProperties['jooq.version']
    configurations {
        main {
            generationTool {
                generator {
                  name = 'org.jooq.codegen.DefaultGenerator'
                  strategy {
                    name = 'org.jooq.codegen.DefaultGeneratorStrategy'
                  }
                  database {
                    name = 'org.jooq.meta.extensions.jpa.JPADatabase'
                    properties {
                      property {
                        key = 'packages'
                        value = 'com.example.jooq.entities'
                      }
                    }
                  }
                  generate {
                  }
                  target {
                    packageName = 'com.example.jooq.entities.jooq'
                    directory = 'target/generated-sources/jooq'
                  }
                }
            }
        }
    }
}
```

Spring Boot pulls in jooq dependencies v. 3.14.7.

**Comment by etiennestuder** [comment]
See this section in the README that explains how to ensure the jooq code generator has the required dependencies available:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#adding-the-database-driver

This example will also give you some indications on how to use the proper configuration for your dependencies:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/configure_jooq_version_from_spring_boot/build.gradle#L14-L21
