### ISSUE TITLE
conditional code generation

### ISSUE THREAD

**Issue by iceback** [etiennestuder/gradle-jooq-plugin#223]
I thought this was working (originally in 3.14):
`jooq {
  version = '3.16.+'
  edition = nu.studer.gradle.jooq.JooqEdition.OSS  // the default (can be omitted)
  def doJooq = true;
  configurations {
    if (referenceDBname.contains("DBNAME_NOT_SET")) { 
      println("HEADS UP: you will need to configure the reference database: " + referenceDBname)
      doJooq = false;
    }
    else {
      println("Generating jOOQ code from " + referenceDBname)
    }
    main {  // name of the jOOQ configuration
      generateSchemaSourceOnCompilation = doJooq
      generationTool {
        logging = org.jooq.meta.jaxb.Logging.INFO
        jdbc {
`
but when DBNAME_NOT_SET is in play, the generated code is delete and then 
`
12:19:05 SEVERE Error in file: /home/rob/gits/gitlab/sgs5/jooq/build/tmp/generateJooq/config.xml. Error : FATAL: database "DBNAME_NOT_SET" does not exist
org.postgresql.util.PSQLException: FATAL: database "DBNAME_NOT_SET" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2787)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:173)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:290)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:400)
	at org.postgresql.Driver.connect(Driver.java:259)
	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:368)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:239)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:234)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:206)

`
Is there a correct approach to conditional code generation?
Thanks.

**Comment by etiennestuder** [comment]
Please provide a fully reproducible example. Until then, I'm closing this issue.
