### ISSUE TITLE
Plugin classpath overrides not properly working in 3.0.1

### ISSUE THREAD

**Issue by anuraaga** [etiennestuder/gradle-jooq-plugin#77]
I use this workaround to allow JOOQ to run on JDK9, which doesn't expose JAXB automatically

```
dependencies {
  jooqRuntime 'javax.activation:activation'
  jooqRuntime 'javax.xml.bind:jaxb-api'
  jooqRuntime 'com.sun.xml.bind:jaxb-core'
  jooqRuntime 'com.sun.xml.bind:jaxb-impl'
}
```

Unfortunately it doesn't seem to work with version 3.0.1 of this plugin. Downgrading to 3.0.0 works fine. Is this an intended change?

**Comment by etiennestuder** [comment]
I don't see right away why 3.0.0 vs. 3.0.1 would be different. Nothing changed with regard to configuration code. If you can provide reproducible steps/example, we will take a look at it. //cc @felipefzdz

**Comment by ben-manes** [comment]
I just ran into this as well when trying to upgrade. I used a more heavy-handed configuration via `tasks.withType(JavaExec)` to opt in a few plugins. 

```
> javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
   - with linked exception:
  [java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
```

**Comment by felipefzdz** [comment]
I was able to reproduce the exception that @ben-manes refers to by executing `generateSampleJooqSchemaSource` on `gradle-jooq-plugin/example/add_jvm_args` with `9.0.1-oracle`. Both for `3.0.0` and `3.0.1` of this plugin.

**Comment by etiennestuder** [comment]
Thanks, @felipefzdz . The work in 3.0.1 having made the difference in behavior never really made sense to me. Given we currently verify correctness of the plugin against Java 8, we should look into the delta to make it work with both Java 8 and Java 9. Let's discuss this coming week.

**Comment by anuraaga** [comment]
Will try to create a small repro but the exception was definitely solved by downgrading to 3.0.0. Note that jooq has never worked with JDK9 without the work around to add jaxb to the classpath

**Comment by etiennestuder** [comment]
Thanks, @anuraaga .

**Comment by anuraaga** [comment]
I have created a small repro based on `add_jvm_args` - actually I just wanted to create a PR for it but the gradle version here is too ancient for JDK9, and trying to update that might lead to a deep rabbit hole (need to upgrade bintray plugin, etc) so created a separate repo.

https://github.com/anuraaga/gradle-jooq-plugin-jdk9

The only changes are

```groovy
buildscript {
    dependencies {
        classpath 'com.sun.xml.bind:jaxb-core:2.3.0.1'
        classpath 'com.sun.xml.bind:jaxb-impl:2.3.0.1'
        classpath 'javax.activation:activation:1.1.1'
        classpath 'javax.xml.bind:jaxb-api:2.3.0'
    }
}
...
dependencies {
  ...
  jooqRuntime 'javax.activation:activation:1.1.1'
  jooqRuntime 'javax.xml.bind:jaxb-api:2.3.0'
  jooqRuntime 'com.sun.xml.bind:jaxb-core:2.3.0.1'
  jooqRuntime 'com.sun.xml.bind:jaxb-impl:2.3.0.1'
```

With JDK10 and JDK9 (tried both)

```bash
$ ./gradlew :generateSampleJooqSchemaSource
```

works but if you change the version of `nu.studer.jooq` to `3.0.1` it doesn't with:

```
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at nu.studer.gradle.jooq.JooqTask.generateConfigurationBytes(JooqTask.groovy:105)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at nu.studer.gradle.jooq.JooqTask.getConfigurationBytes(JooqTask.groovy:73)
        at nu.studer.gradle.jooq.JooqTask.getConfigurationHash(JooqTask.groovy:66)
        at nu.studer.gradle.jooq.JooqTask_Decorated.getConfigurationHash(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:83)
        ... 33 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
        ... 47 more
```

**Comment by etiennestuder** [comment]
This will be fixed in 3.0.2. Thanks @anuraaga .

**Comment by etiennestuder** [comment]
@anuraaga By now, 3.0.2 has been released. Can you confirm things are working fine now for you?

**Comment by ikovalyov** [comment]
no, it didn't
I had to add 
```
        classpath 'com.sun.xml.bind:jaxb-core:2.3.0.1'
        classpath 'com.sun.xml.bind:jaxb-impl:2.3.0.1'
        classpath 'javax.activation:activation:1.1.1'
        classpath 'javax.xml.bind:jaxb-api:2.3.0'
```
To both dependencies to make plugin work in java 10

**Comment by etiennestuder** [comment]
@ikovalyov What you write above as the workaround is what @anuraaga was also writing above, and he confirmed no more exception is happening with 3.0.2 (which is what triggered this Github issue). You still have to add those dependencies manually given they do not ship in JDK 9 and JDK 10 but they do ship in JDK 8.

**Comment by ikovalyov** [comment]
@etiennestuder I guess it's good idea to add it to the "installation" section of the readme.
Thanks.

**Comment by elwaxoro** [comment]
+1 for adding this to the readme, spent too long trying to debug issues upgrading from JDK8 to JDK10. eventually found this ticket. specifically: the bit about adding the xml dependencies to the buildscript section of the build.gradle. having them in the main dependencies section alone is insufficient.

**Comment by etiennestuder** [comment]
As of gradle-jooq-plugin 3.0.3, the JAXB implementation dependencies do not need to be specified anymore when using JDK 9 or higher.
