### ISSUE TITLE
Plugin is unable to find the configured database (Your configured database type was not found)

### ISSUE THREAD

**Issue by swaechter** [etiennestuder/gradle-jooq-plugin#85]
Hey there

I was checking out jOOQ today and found your plugin. Based on the documentation and an older 2 version I came up with this Gradle build configuration:

```
`buildscript {
    repositories {
        mavenCentral()
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {
        classpath "nu.studer:gradle-jooq-plugin:3.0.2"
        classpath 'org.jooq:jooq:3.11.4' // Not sure if required at all
        classpath "org.jooq:jooq-meta:3.11.4" // Not sure if required at all --> dependency of meta-extensions
        classpath "org.jooq:jooq-meta-extensions:3.11.4"
        classpath "org.jooq:jooq-codegen:3.11.4"
    }
}

apply plugin: 'java'
apply plugin: 'nu.studer.jooq'

sourceCompatibility = 1.8
version = '0.0.1'

repositories {
    mavenCentral()
}

dependencies {
    runtime 'org.postgresql:postgresql:42.2.0'
    compile 'org.jooq:jooq:3.11.4'
    //compile 'org.jooq:jooq-meta:3.11.4'
    //compile 'org.jooq:jooq-meta-extensions:3.11.4'
    //compile "org.jooq:jooq-codegen:3.11.4"
}

jooq {
    edition = "OSS"
    version = "3.11.4"
    bookstore(sourceSets.main) {
        generator {
            name = 'org.jooq.codegen.DefaultGenerator'
            strategy {
                name = 'org.jooq.codegen.DefaultGeneratorStrategy'
            }
            database {
                name = 'org.jooq.meta.extensions.ddl.DDLDatabase'
                properties {
                    property {
                        key = 'scripts'
                        value = 'src/main/resources/database.sql'
                    }
                }
            }
            generate {
                pojos = true
                javaTimeTypes = true
                sequences = true
            }
            target {
                packageName = 'ch.swaechter.bookstore'
                directory = 'src/main/generated/java'
            }
        }
    }
}
```

Executing this on the command line via ` ./gradlew generateBookstoreJooqSchemaSource` on a Linux with OpenJDK 8 results in the following error:

```bash
swaechter@debian:~/Nextcloud/Workspace_Java/jooq-bookstore$ ./gradlew generateBookstoreJooqSchemaSource

> Task :generateBookstoreJooqSchemaSource FAILED
Sep 07, 2018 12:12:37 PM org.jooq.tools.JooqLogger info
INFO: Initialising properties  : /home/swaechter/Nextcloud/Workspace_Java/jooq-bookstore/build/tmp/generateBookstoreJooqSchemaSource/config.xml
Sep 07, 2018 12:12:37 PM org.jooq.tools.JooqLogger warn
WARNING: Type not found           : Your configured database type was not found. This can have several reasons:
- You want to use a commercial jOOQ Edition, but you pulled the Open Source Edition from Maven Central.
- You have mis-typed your class name.
Sep 07, 2018 12:12:37 PM org.jooq.tools.JooqLogger error
SEVERE: Cannot read /home/swaechter/Nextcloud/Workspace_Java/jooq-bookstore/build/tmp/generateBookstoreJooqSchemaSource/config.xml. Error : Your configured database type was not found. This can have several reasons:
- You want to use a commercial jOOQ Edition, but you pulled the Open Source Edition from Maven Central.
- You have mis-typed your class name.
java.lang.ClassNotFoundException: Your configured database type was not found. This can have several reasons:
- You want to use a commercial jOOQ Edition, but you pulled the Open Source Edition from Maven Central.
- You have mis-typed your class name.
        at org.jooq.codegen.GenerationTool.loadClass(GenerationTool.java:855)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:362)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:220)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:192)
Caused by: java.lang.ClassNotFoundException: org.jooq.meta.extensions.ddl.DDLDatabase
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.jooq.codegen.GenerationTool.loadClass(GenerationTool.java:819)
        ... 3 more



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateBookstoreJooqSchemaSource'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
swaechter@debian:~/Nextcloud/Workspace_Java/jooq-bookstore$
```

You can find my repository here: https://github.com/swaechter/jooq-bookstore

In previous issues I saw that there was some package relocation from utils, but I checked all class paths via https://search.maven.org/:

* fc:org.jooq.codegen.DefaultGenerator --> jooq:codegen:3.11.4
* fc:org.jooq.codegen.DefaultGeneratorStrategy --> jooq-codegen:3.11.4
* fc:org.jooq.meta.extensions.ddl.DDLDatabase --> jooq-meta-extensions:3.11.4

These two dependencies should be provided in the build classpath. Is this a bug/problem in the configuration or am I doing something wrong?

**Comment by swaechter** [comment]
Mistake on my side: I had to add the PostgreSQL driver as `jooqRuntime` dependency in `dependencies` and not in the build section:

```
dependencies {
    compile 'org.postgresql:postgresql:42.2.0'
    compile 'org.jooq:jooq:3.11.4'
    jooqRuntime group: 'org.jooq', name: 'jooq-meta-extensions', version: '3.11.4'
}
```
