### ISSUE TITLE
build.gradle.kts ClassNotFoundException postgresql Driver

### ISSUE THREAD

**Issue by rdinkel** [etiennestuder/gradle-jooq-plugin#89]
Hello, I tried to move from groovy gradle to kotlin dsl, but I have an issue with the finding of the postgres driver and I can not figure out whats wrong. Does I use your plugin in the kotlin dsl right?

used gradle version 5

Groovy (works)
```gradle
plugins {
    id 'io.vertx.vertx-plugin' version '0.1.0'
    id 'org.jetbrains.kotlin.jvm' version '1.2.71'
    id "org.flywaydb.flyway" version "5.2.0"
    id "nu.studer.jooq" version "3.0.2"
}

repositories {
    mavenCentral()
}

dependencies {
    compile 'io.vertx:vertx-lang-kotlin'
    compile 'io.vertx:vertx-web'
    compile 'io.vertx:vertx-web-client'
    compile 'io.vertx:vertx-junit5'
    testCompile group: 'org.assertj', name: 'assertj-core', version: '3.9.0'
    compile ('org.jetbrains.kotlin:kotlin-stdlib-jdk8') {
        exclude group: 'org.jetbrains.kotlin', module : 'kotlin-stdlib-jre7'
        exclude group: 'org.jetbrains.kotlin', module : 'kotlin-stdlib-jre8'
    }

    // https://mvnrepository.com/artifact/org.jooq/jooq
    compile group: 'org.jooq', name: 'jooq', version: '3.11.5'
    // https://mvnrepository.com/artifact/org.jooq/jooq-meta
    compile group: 'org.jooq', name: 'jooq-meta', version: '3.11.5'
    // https://mvnrepository.com/artifact/org.jooq/jooq-codegen
    compile group: 'org.jooq', name: 'jooq-codegen', version: '3.11.5'
    compile 'org.jooq:jooq'
    // jooq needs kotlin reflects for mapping records into kclasses
    // https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-reflect
    compile group: 'org.jetbrains.kotlin', name: 'kotlin-reflect', version: '1.2.71'


    // https://mvnrepository.com/artifact/org.postgresql/postgresql
    // for flyway
    compile group: 'org.postgresql', name: 'postgresql', version: '42.2.5'
    // for jooq
    jooqRuntime group: 'org.postgresql', name: 'postgresql', version: '42.2.5'
}

vertx {
    mainVerticle = "com.redbricks.verticles.MainVertical"
    vertxVersion = "3.5.4"
}

jooq {
    version = '3.11.5' // the default (can be omitted)
    edition = 'OSS'

    csmart(sourceSets.main) {
        jdbc {
            driver = 'org.postgresql.Driver'
            url = 'jdbc:postgresql://localhost:32768/postgres'
            user = 'postgres'
            password = ''
            schema = 'public'
        }
        generator {
            name = 'org.jooq.codegen.DefaultGenerator'
            strategy {
                name = null
                matchers {
                  tables {
                      table {
                          expression = 'building'
                          recordImplements = 'com.rustyrobots.IBuildingJava'
//                          recordImplements = 'com.redbricks.verticles.entities.interfaces.IBuilding'
                      }
                  }
                }
            }
            database {
                name = 'org.jooq.meta.postgres.PostgresDatabase'
                inputSchema = 'public'
                customTypes {
                    customType {
                        name = 'com.fasterxml.jackson.databind.JsonNode'
                        converter = 'csmart.api.config.db.PostgresJSONJacksonJsonNodeBinding'
                    }
                }
                forcedTypes {
                    forcedType {
                        name = 'com.fasterxml.jackson.databind.JsonNode'
                        expression = 'public\\.users\\.address'
                    }
                }
            }
            generate {
                relations = true
                deprecated = false
                records = true
                immutablePojos = false
                fluentSetters = true
            }
        }
    }
}
generateCsmartJooqSchemaSource.dependsOn flywayMigrate
project.tasks.getByName('compileKotlin').dependsOn += 'generateCsmartJooqSchemaSource'

flyway {
    url = 'jdbc:postgresql://localhost:32768/postgres'
    user = 'postgres'
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```

But this is not working:
```kotlin
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import nu.studer.gradle.jooq.JooqConfiguration
import nu.studer.gradle.jooq.JooqEdition
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.jooq.codegen.GenerationTool
import org.jooq.meta.jaxb.Generator
import org.jooq.meta.jaxb.Jdbc
import org.jooq.meta.jaxb.Target
import org.jooq.meta.jaxb.Database

// Versions
val jooQVersion = "3.11.5"
val kotlinVersion = "1.3.11"
val postgresVersion = "42.2.5"
val vertxVersion = "3.6.2"

val dbUser = "postgres"
val dbPassword = "postgres"
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM
    id("org.jetbrains.kotlin.jvm").version("1.3.11")
    id("org.flywaydb.flyway").version("5.2.4")
    id("nu.studer.jooq").version("3.0.2")
    id("io.vertx.vertx-plugin").version("0.1.0")
    id("com.github.johnrengelman.shadow").version("4.0.3")
    // Apply the application to add support for building a CLI application
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JDK 8 standard library
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlin", "kotlin-reflect", kotlinVersion)

    implementation("io.vertx", "vertx-lang-kotlin", vertxVersion)
    implementation("io.vertx", "vertx-web", vertxVersion)
    implementation("io.vertx", "vertx-web-client", vertxVersion)
    implementation("io.vertx", "vertx-junit5", vertxVersion)

    compile("org.jooq", "jooq", jooQVersion)
    compile("org.jooq", "jooq-meta", jooQVersion)
    compile("org.jooq", "jooq-codegen", jooQVersion)
    compile ("org.jooq:jooq")

    compile("org.postgresql", "postgresql", postgresVersion)
//    jooqRuntime("org.postgresql", "postgresql", postgresVersion)
    jooqRuntime("'org.postgresql", "postgresql", "42.2.5")

    // Use the Kotlin test library
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

vertx {
    mainVerticle = "com.redbricks.verticles.MainVertical"
    vertxVersion = "3.6.2"
}

application {
    // Define the main class for the application
    mainClassName = "soeVertx.AppKt"
}

flyway {
    url = "jdbc:postgresql://localhost:5432/postgres"
    user = dbUser
    password = dbPassword
}

jooq {
    sourceSets{
        main {
            withGroovyBuilder{
                val configuration = org.jooq.meta.jaxb.Configuration().apply {
                    jdbc = Jdbc().apply {
                        driver = "org.postgresql.Driver"
                        url = "jdbc:postgresql://localhost:32768/postgres"
                        user = "postgres"
                        password = "postgres"
                        schema = "public"
                    }
                    generator = Generator().apply {
                        //            generator

                        database = Database().apply {
                            name = "org.jooq.meta.postgres.PostgresDatabase"
                            includes = ".*"
                            excludes = "schema_version"
                            inputSchema = "public"
                        }
                        target = Target().apply {
                            packageName = "org.jooq.codes.foobar.cv"
                            directory = "src/main/kotlin"
                        }
                    }
                }
                GenerationTool.generate(configuration)
            }
        }
    }
}


tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}
```

Exception is:
```
java.lang.ClassNotFoundException: org.postgresql.Driver
	at org.jooq.codegen.GenerationTool.loadClass(GenerationTool.java:819)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:310)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:220)
```

**Comment by dustinsand** [comment]
Try adding postgresql dependency to buildScript. Resolved the NotFoundException for me, but the next issue I ran into was the generateMainJooqSchemaSource task was not available.

buildscript {
    dependencies {
        classpath("org.postgresql:postgresql:42.2.5")
    }
}

**Comment by rdinkel** [comment]
Did you fixed your issue with the missing task? 
Sorry for late response, very busy :/

**Comment by etiennestuder** [comment]
@rdinkel The plugin currently is not explicitly intended to work with the Kotlin DSL, and thus it is too cumbersome for me to investigate why it is not working with your posted Kotlin script.

As a workaround, I suggest you keep the Groovy script that already works and reference it from your Kotlin build scripts via `apply(from = "jooq.gradle")`.

**Comment by etiennestuder** [comment]
As of 5.x, the gradle-jooq-plugin supports the Gradle Kotlin DSL as a first-class citizen. See the README file:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md

See this complete example written with the Gradle Kotlin DSL:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_kotlin_dsl/build.gradle.kts
